### ISSUE TITLE
Stremio encountered an error with this media.

### ISSUE THREAD

**Issue by Telkaoss** [g0ldyy/comet#104]
Hello, I have self-hosted this addon, but I can't watch the movies; I always receive the message "Stremio encountered an error with this media." I tried with Prowlarr and Jackett. I can't find anything helpful in the Comet and Jackett logs.

It's as if Comet couldn't reach RD (the API key is correct). The other self-hosted addons are working.

PS: It doesn't add the torrent to RD.

I'm not sure if this is related
console web stremio : 

```
Mixed Content: Surclassement de la requête d’affichage non sécurisée « http://domain.tld/*********/1 » par l’utilisation de « https » 1
Blocage du chargement du contenu mixte actif (mixed active content) « http://domain.tld/**********/1 » web.stremio.com:1:1303
```
On the Stremio browser, the video shows "uncached.mp4."

**Comment by g0ldyy** [comment]
problème de configuration de ton côté 🫡
ce n'est pas un problème venant de Comet
t'as setup Comet comment? derrière un reverse proxy?

**Comment by Telkaoss** [comment]
oui, j'utilise Traefik et cette configuration là :

`  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencryptresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.email=mail@mail.com"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard Traefik`
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt" 
    networks:
      - proxy

et ça pour comet  :

`  Comet:
    image: g0ldyy/comet
    container_name: comet
    restart: unless-stopped
#     ports: #uncomment this if you're not using a reverse proxy
#     - 8000:8000
    env_file: #uncomment this if you want to use a .env file, otherwise update below in environment
      - config.env
#    environment: #comment this out/remove if you want to use a .env file
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.comet.entrypoints=http"
      - "traefik.http.routers.comet.rule=Host(`comet.domain.com`)"
      - "traefik.http.middlewares.comet-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.comet.middlewares=comet-https-redirect"
      - "traefik.http.routers.comet-secure.entrypoints=https"
      - "traefik.http.routers.comet-secure.rule=Host(`comet.domain.com`)"
      - "traefik.http.routers.comet-secure.tls=true"
      - "traefik.http.routers.comet.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.comet-secure.service=comet"
      - "traefik.http.services.comet.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"`

**Comment by Telkaoss** [comment]
oui j'ai utilisé traefik pour le reverse proxy attaché au compose.yaml

```
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencryptresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.email=mail@mail.com"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard Traefik`
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt" # Volume pour stocker les certificats
    networks:
      - proxy
```

**Et pour comet**
```

  Comet:
    image: g0ldyy/comet
    container_name: comet
    restart: unless-stopped
#     ports: #uncomment this if you're not using a reverse proxy
#     - 8000:8000
    env_file: #uncomment this if you want to use a .env file, otherwise update below in environment
      - config.env
#    environment: #comment this out/remove if you want to use a .env file
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.comet.entrypoints=http"
      - "traefik.http.routers.comet.rule=Host(`.comet.domain.com`)"
      - "traefik.http.middlewares.comet-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.comet.middlewares=comet-https-redirect"
      - "traefik.http.routers.comet-secure.entrypoints=https"
      - "traefik.http.routers.comet-secure.rule=Host(`comet.domain.com`)"
      - "traefik.http.routers.comet-secure.tls=true"
      - "traefik.http.routers.comet.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.comet-secure.service=comet"
      - "traefik.http.services.comet.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy" 
```
