### ISSUE TITLE
Using Gluetun instead of Warp

### ISSUE THREAD

**Issue by luttman** [g0ldyy/comet#125]
Hello, Im using Gluetun instead of using Warp, i have my own vpnprovider, and im trying to get it to work with gluetun. Jackett and everything else works, but with comet i get
[Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address in use,

```
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP=192.168.1.3
      - WIREGUARD_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=bFHGcxUTy3R+uBnTlRLz6CshmPNMXDlWVuOb0MfT4GM=
      - WIREGUARD_PRIVATE_KEY=4DYa5l/eD9lKRRP2BPIWAF0Q8KFiFQsIbcJmg4pAuWM=
      - WIREGUARD_PRESHARED_KEY=zokbC7ZnVAWSgHgt/zPE7RV4dbG0xQ3198b0nHPeATI=
      - WIREGUARD_ADDRESSES=10.8.0.5/24
    ports: #uncomment this if you're not using a reverse proxy
      - 8000:8000/tcp

# This is a Comet full stack with Zilean, flaresolverr, Warp, Prowlarr/Jackett deployed through docker compose using Traefik as a reverse proxy.
  Comet:
    image: g0ldyy/comet
    container_name: comet
    restart: unless-stopped
    network_mode: "service:gluetun"
#    ports: #uncomment this if you're not using a reverse proxy
#     - 8000:8000
#    env_file: #uncomment this if you want to use a .env file, otherwise update below in environment
#      - .env
    environment: #comment this out/remove if you want to use a .env file
      - ADDON_ID=stremio.comet.fast # for Stremio
      - ADDON_NAME=Comet # for Stremio
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - FASTAPI_WORKERS=2 # remove to destroy CPU -> max performances
      - DATABASE_PATH=data/comet.db # only change it if you know what it is - folders in path must exist
      - CACHE_TTL=86400 # cache duration in seconds
#      - DEBRID_PROXY_URL=http://warp:1080 # https://github.com/cmj2002/warp-docker to bypass Debrid Services and Torrentio server IP blacklist 
      - INDEXER_MANAGER_TYPE=jackett # or prowlarr
      - INDEXER_MANAGER_URL=http://jackett:9117 # or http://prowlarr:9696
      - INDEXER_MANAGER_API_KEY=*SuperSecret*
      - INDEXER_MANAGER_TIMEOUT=60 # maximum time to obtain search results from indexer manager in seconds
      - INDEXER_MANAGER_INDEXERS=["EZTV", "YTS", "TheRARBG", "BitSearch", "ThePirateBay"]
      - GET_TORRENT_TIMEOUT=10 # maximum time to obtain the torrent info hash in seconds
      - ZILEAN_URL=http://zilean:8181 # for DMM search - https://github.com/iPromKnight/zilean
      - ZILEAN_TAKE_FIRST=500 # only change it if you know what it is
      - SCRAPE_TORRENTIO=True # or False scrape Torrentio
      - CUSTOM_HEADER_HTML=None # only set it if you know what it is
      - PROXY_DEBRID_STREAM=TRUE # or False Proxy Debrid Streams (very useful to use your debrid service on multiple IPs at same time)
      - PROXY_DEBRID_STREAM_PASSWORD=*SuperSecreT*# Secret password to enter on configuration page to prevent people from abusing your debrid stream proxy
      - 
```
